apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-solrcloud-nodeport
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: solr-cloud
    {{- include "solr-cloud.labels" . | nindent 4 }}
spec:
  type: NodePort
  selector:
    technology: solr-cloud
    solr-cloud: {{ .Release.Name }}
  ports:
    - name: http
      port: 8983
      targetPort: 8983
      {{- if and .Values.service .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
      protocol: TCP
