apiVersion: solr.apache.org/v1beta1
kind: SolrCloud
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  solrSecurity:
    authenticationType: Basic
  dataStorage:
    persistent:
      reclaimPolicy: {{ .Values.solr.storage.reclaimPolicy }}
      pvcTemplate:
        spec:
          storageClassName: {{ .Values.solr.storage.className }}
          resources:
            requests:
              storage: {{ .Values.solr.storage.size }}
  replicas: {{ .Values.solr.replicas }}
  solrImage:
    tag: {{ .Values.solr.image.tag }}
  solrJavaMem: {{ .Values.solr.javaMem | quote }}
  solrOpts: {{ .Values.solr.opts | quote }}
  solrGCTune: {{ .Values.solr.gcTune | quote }}
  customSolrKubeOptions:
    podOptions:
      resources:
        limits:
          memory: {{ .Values.solr.resources.limits.memory }}
          cpu: {{ .Values.solr.resources.limits.cpu }}
        requests:
          memory: {{ .Values.solr.resources.requests.memory }}
          cpu: {{ .Values.solr.resources.requests.cpu }}
      volumes:
      {{- if .Values.solr.secret.enabled }}
        - name: keys-secret
          source:
            secret:
              secretName: {{ .Values.solr.secret.name }}
          defaultContainerMount:
            name: keys-secret
            mountPath: {{ .Values.solr.secret.mountPath }}
      {{- end }}
      {{- if .Values.solr.bioSolr.enabled}}
        - name: bio-solr-volume
          {{- include "bioSolr.volume.source" . | nindent 8 }}
          defaultContainerMount:
            name: bio-solr-volume
            mountPath: /var/solr/data/filestore/biosolr
            subPath: fg/atlas/biosolr
        - name: scatlas-owl-volume
          {{- include "bioSolr.volume.source" . | nindent 8 }}
          defaultContainerMount:
            name: scatlas-owl-volume
            mountPath: /var/solr/data/userfiles/scatlas.owl
            subPath: fg/atlas/biosolr/scatlas.owl
      {{- end }}
  zookeeperRef:
    provided:
      persistence:
        spec:
          storageClassName: {{ .Values.zookeeper.storage.className }}
          resources:
            requests:
              storage: {{ .Values.zookeeper.storage.size }}
      replicas: {{ .Values.zookeeper.replicas }}
      zookeeperPodPolicy:
        resources:
          limits:
            memory: {{ .Values.zookeeper.resources.limits.memory }}