# values for gxa test env
environment: test

loggingLevel: DEBUG

tomcat:
  createSecret: true
  debug:
    enabled: true

jdbc:
  username: atlasprd3
  populator:
    enabled: true
  url: "jdbc:postgresql://pgsql-hlvm-137.ebi.ac.uk:5432/gxpscxapro"
  createSecret: true



solr:
  namespace: scxa-staging-solrcloud
  user: admin
  createSecret: true

nfs:
  experimentsPath: "/ifs/public/ro/scxa_codon/atlas_sc_experiments"
