apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mongodb.fullname" . }}-secret
  labels:
    {{- include "mongodb.labels" . | nindent 4 }}
    app.kubernetes.io/component: mongodb
type: Opaque
stringData:
  root-password: {{ .Values.auth.rootPassword | quote }}
  {{- if .Values.auth.database }}
  database: {{ .Values.auth.database | quote }}
  {{- end }}
  {{- if .Values.auth.username }}
  username: {{ .Values.auth.username | quote }}
  password: {{ .Values.auth.password | quote }}
  {{- end }}


