apiVersion: v1
kind: Pod
metadata:
  namespace: gxa-jenkins
spec:
  securityContext:
    fsGroup: 1000
  containers:
    - name: jnlp
      resources:
        requests:
          memory: "256Mi"
          cpu: "200m"
        limits:
          memory: "512Mi"
          cpu: "500m"
    - name: python
      image: python:3.12-bookworm
      command: ["/bin/sh", "-c", "sleep 2h"]
      resources:
        requests:
          memory: "512Mi"
          cpu: "200m"
        limits:
          memory: "1Gi"
          cpu: "1000m"
