apiVersion: v1
kind: Pod
metadata:
  namespace: gxa-jenkins
spec:
  serviceAccountName: jenkins-cloud
  securityContext:
    fsGroup: 1000
  containers:
    - name: jnlp
      resources:
        requests:
          memory: "512Mi"
          cpu: "500m"
        limits:
          memory: "512Mi"
          cpu: "500m"
    - name: helm
      image: dtzar/helm-kubectl:3.14
      command: ["/bin/sh", "-c", "sleep 2h"]
      resources:
        requests:
          memory: "256Mi"
          cpu: "500m"
        limits:
          memory: "512Mi"
          cpu: "500m"
