solr:
  replicas: 4
  image:
    tag: 8.7.0
  javaMem: "-Xms2000m -Xmx3000m"
  opts: "-Denable.packages=true -Dblob.max.size.mb=100 -Dsolr.port.advertise=8983"
  gcTune: "-XX:SurvivorRatio=4 -XX:TargetSurvivorRatio=90 -XX:MaxTenuringThreshold=8"
  resources:
    limits:
      memory: 4Gi
      cpu: 2
    requests:
      memory: 3Gi
      cpu: 1
  storage:
    className: standard-nfs-production
    size: 20Gi
    reclaimPolicy: Retain
  secret:
    name: gxa-solrcloud-package-store-keys
    mountPath: /keys

zookeeper:
  replicas: 3
  storage:
    className: standard-nfs-production
    size: 500Mi
  resources:
    limits:
      memory: 512Mi
      cpu: 0.5
    requests:
      memory: 512Mi
      cpu: 0.5

service:
   nodePort: null   # Assign a port (30000–32767)
