# scxa-test
solr:
  replicas: 4
  image:
    tag: 8.7.0
  javaMem: "-Xms2000m -Xmx3000m"
  opts: "-Denable.packages=true -Dblob.max.size.mb=100 -Dsolr.port.advertise=8983 -Dsolr.max.booleanClauses=100000000 -Dsolr.allowPaths=/var/solr/backup"
  gcTune: "-XX:SurvivorRatio=4 -XX:TargetSurvivorRatio=90 -XX:MaxTenuringThreshold=8"
  # resources:
  #   limits:
  #     memory: 3Gi
  #     cpu: 2
  #   requests:
  #     memory: 2Gi
  #     cpu: 1
  # storage:
  #   className: standard-nfs-production
  #   size: 20Gi
  #   reclaimPolicy: Retain
  secret:
    enabled: false
    name: scxa-solrcloud-package-store-keys
    mountPath: /keys
  bioSolr:
    enabled: true

zookeeper:
  replicas: 3
  storage:
    className: standard-nfs-production
    size: 500Mi
  resources:
    limits:
      memory: 512Mi

service:
   nodePort: null   # Assign a port (30000–32767)
