apiVersion: v1
kind: Service
metadata:
  namespace: jenkins-gene-expression
  name: gxa-postgres-headless
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: postgresql
      port: 5432
      targetPort: postgresql
      protocol: TCP
  selector:
    app: postgres
