apiVersion: v1
kind: Pod
metadata:
  name: openjdk-scxa-solrcloud-shell
  namespace: jenkins-gene-expression
spec:
  volumes:
    - name: bioentity-properties-vol
      persistentVolumeClaim:
        claimName: bioentity-properties-rox
    - name: gradle-ro-dep-cache
      persistentVolumeClaim:
        claimName: gradle-7.0-ro-dep-cache-rox
    - name: scxa-data-vol
      persistentVolumeClaim:
        claimName: scxa-data-rox
    - name: scxa-solrcloud-keys
      secret:
        secretName: scxa-solrcloud-package-store-keys
  containers:
    - name: shell
      image: openjdk:11
      workingDir: "/root"
      env:
        - name: GRADLE_RO_DEP_CACHE
          value: "/root/gradle-ro-dep-cache"
      resources:
        requests:
          memory: 6Gi
          ephemeral-storage: 8Gi
        limits:
          memory: 8Gi
      args:
        - bash
      stdin: true
      stdinOnce: true
      tty: true
      volumeMounts:
        - mountPath: /scxa-data
          name: scxa-data-vol
          readOnly: true
        - mountPath: /keys
          name: scxa-solrcloud-keys
          readOnly: true
        - mountPath: /atlas-data/bioentity_properties
          name: bioentity-properties-vol
          readOnly: true
        - mountPath: /root/gradle-ro-dep-cache
          name: gradle-ro-dep-cache
          readOnly: true
    - name: postgres
      image: postgres:10-alpine
      env:
        - name: POSTGRES_USER
          value: foobar
        - name: POSTGRES_PASSWORD
          value: foobar
