apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gxa-data-rwo
  namespace: jenkins-gene-expression
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
apiVersion: batch/v1
kind: Job
metadata:
  name: gxa-data-populator
  namespace: jenkins-gene-expression
spec:
  template:
    spec:
      volumes:
        - name: gxa-data-vol
          persistentVolumeClaim:
            claimName: gxa-data-rwo
      containers:
      - name: gxa-data-ftp
        image: takkatakka/lftp
        env:
        - name: EXP_IDS
          value: "E-ERAD-475 E-GEOD-40611 E-GEOD-43049 E-GEOD-46858 E-MAXD-6 E-MEXP-1810 E-MEXP-1968 E-MTAB-1913 E-MTAB-2770 E-MTAB-2836 E-MTAB-2909 E-MTAB-3827 E-MTAB-3834 E-MTAB-4401 E-MTAB-451 E-MTAB-4559 E-MTAB-5128 E-MTAB-5200 E-MTAB-5422 E-MTAB-5423 E-MTAB-5633 E-MTAB-5941 E-TABM-713 E-MTAB-5214 E-PROT-1 E-MTAB-4106 E-PROT-28 E-PROT-39"
        command: ['sh', '-c']
        args:
          - lftp -e "get /pub/databases/arrayexpress/data/atlas/atlas-ci/species-properties.json -o /gxa-data; exit" ftp.ebi.ac.uk;
            lftp -e "get /pub/databases/arrayexpress/data/atlas/atlas-ci/release-metadata.json -o /gxa-data; exit" ftp.ebi.ac.uk;
            for EXP_ID in ${EXP_IDS}; do lftp -e "mirror -vvv --exclude-glob=archive/* /pub/databases/microarray/data/atlas/experiments/${EXP_ID} /gxa-data/magetab/${EXP_ID}; exit" ftp.ebi.ac.uk; done;
        volumeMounts:
          - mountPath: "/gxa-data"
            name: gxa-data-vol
      restartPolicy: Never
  backoffLimit: 4

