apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bioentity-properties-rwo
  namespace: jenkins-gene-expression
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
