apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bulk-analytics-jsonl-rwo
  labels:
    {{- include "app.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  storageClassName: standard-nfs-production 
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi