apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.fullname" . }}-config
  labels:
    {{- include "app.labels" . | nindent 4 }}
data:
  server.xml: |
    <Server port="8005" shutdown="SHUTDOWN">
      <Service name="Catalina">
        <Connector port="{{ .Values.tomcat.port }}" 
                   protocol="HTTP/1.1"
                   connectionTimeout="20000"
                   redirectPort="8443" />
        <Engine name="Catalina" defaultHost="localhost">
          <Host name="localhost" appBase="webapps"
                unpackWARs="true" autoDeploy="true">
          </Host>
        </Engine>
      </Service>
    </Server> 

  configuration.properties: |
    data.files.location = {{- include "app.dataDir" . }}
    experiment.files.location = {{- include "app.experimentsDir" . }}
    experiment.design.location= {{ include "app.expdesignDir" . }}

  experiment_ids: {{ .Values.experiment_ids}}


