apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.fullname" . }}-config
  labels:
    {{- include "app.labels" . | nindent 4 }}
data:
  server.xml: |
    <Server port="8005" shutdown="SHUTDOWN">
      <Service name="Catalina">
        <Connector port="{{ .Values.tomcat.port }}" 
                   protocol="HTTP/1.1"
                   connectionTimeout="20000"
                   redirectPort="8443" />
        <Engine name="Catalina" defaultHost="localhost">
          <Host name="localhost" appBase="webapps"
                unpackWARs="true" autoDeploy="true">
          </Host>
        </Engine>
      </Service>
    </Server> 

  configuration.properties: |
    data.files.location = {{- include "app.dataDir" . }}
    experiment.files.location = {{- include "app.experimentsDir" . }}
    experiment.design.location= {{ include "app.expdesignDir" . }}

  experiment_ids: {{ .Values.experiment_ids}}

  species: |
    danio_rerio homo_sapiens equus_caballus drosophila_melanogaster
    caenorhabditis_elegans mus_musculus oryza_indica anas_platyrhynchos
    oryza_sativa brachypodium_distachyon schistosoma_mansoni zea_mays
    saccharomyces_cerevisiae schizosaccharomyces_pombe

  {{- if and (not (empty .Values.solr)) .Values.solr.createSecret }}
  # Solr configuration
  SOLR_HOST: "{{ include "app.solrHost" . }}"
  SOLR_ZK_HOSTS: "{{ include "app.solrZkHosts" . }}"
  SOLR_BIOENTITIES_COLLECTION: "{{ .Values.solr.bioentities.collection  }}"
  SOLR_BULK_ANALYTICS_NUM_SHARDS: "{{ .Values.solr.bulkAnalytics.numShards | default "4" }}"
  SOLR_NUM_SHARDS: "{{ .Values.solr.numShards | default "4" }}"
  SOLR_TIMEOUT: "{{ .Values.solr.timeout | default "30000" }}"
  {{- end }}

