apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gxa.fullname" . }}
  labels:
    {{- include "gxa.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "gxa.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "gxa.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "gxa.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.tomcat.httpPort }}
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          #   initialDelaySeconds: 30
          #   periodSeconds: 30
          #   timeoutSeconds: 10
          #   failureThreshold: 20
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          #   initialDelaySeconds: 30
          #   periodSeconds: 30
          #   timeoutSeconds: 10
          #   failureThreshold: 20
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          # app data mounts
            - name: gxa-codon-volume
              mountPath: /srv/gxa/data/gxa_codon
              readOnly: true
            - name: experiments-snapshot
              mountPath: /srv/gxa/data/gxa/magetab
              readOnly: true
            - name: gxa-volume
              mountPath: /srv/gxa/data/gxa/release-metadata.json
              subPath: release-metadata.json
              readOnly: true
            - name: gxa-codon-volume
              mountPath: /srv/gxa/data/gxa/species-properties.json
              subPath: species-properties.json  
              readOnly: true
            - name: bioentity-properties-volume
              mountPath: /srv/gxa/data/bioentity_properties
              subPath: fg/atlas/bioentity_properties
              readOnly: true
            - name: gxa-expdesign-vol
              mountPath: /srv/gxa/data/gxa/expdesign
            # webapp properties mounts
            - name: configuration-properties
              mountPath: /webapp-properties/configuration.properties
              subPath: configuration.properties
            - name: gxa-secrets
              mountPath: /webapp-properties/jdbc.properties
              subPath: jdbc.properties
            - name: gxa-secrets
              mountPath: /webapp-properties/solr.properties
              subPath: solr.properties
            # tomcat config mounts
            - name: gxa-secrets
              mountPath: /usr/local/tomcat/conf/tomcat-users.xml
              subPath: tomcat-users.xml
            - name: tomcat-logs
              mountPath: /usr/local/tomcat/logs
            - name: tomcat-work
              mountPath: /usr/local/tomcat/work
            - name: tomcat-webapps
              mountPath: /usr/local/tomcat/webapps
            - name: tomcat-config
              mountPath: /usr/local/tomcat/conf/Catalina
      volumes:
        - name: gxa-volume
          nfs:
            server: {{ .Values.nfs.server }}
            path: /ifs/public/ro/gxa
        - name: gxa-codon-volume
          nfs:
            server: {{ .Values.nfs.server }}
            path: /ifs/public/ro/gxa_codon
        - name: bioentity-properties-volume
          nfs:
            server: {{ .Values.nfs.server }}
            path: /ifs/public/services
        - name: gxa-expdesign-vol
          persistentVolumeClaim:
            claimName: gxa-expdesign-rwo
        - name: experiments-snapshot
          emptyDir: {}
        - name: configuration-properties
          configMap:
            name: {{ include "gxa.fullname" . }}-config
            items:
              - key: configuration.properties
                path: configuration.properties
        - name: tomcat-server-config
          configMap:
            name: {{ include "gxa.fullname" . }}-config
            items:
              - key: server.xml
                path: server.xml
        - name: gxa-secrets
          secret:
            secretName: {{ include "gxa.fullname" . }}-secrets
        - name: tomcat-logs
          emptyDir: {}
        - name: tomcat-work
          emptyDir: {}
        - name: tomcat-webapps
          emptyDir: {}
        - name: tomcat-config
          emptyDir: {}
      initContainers:
        - name: gxa-init-experiments-snapshot
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: busybox
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["sh"]
          args:
            - "-c"
            - |
              set -vx
              ln -s -v /srv/gxa/data/gxa_codon/.snapshot/{{ .Values.nfs.snapshotComponent }}/experiments/* /experiments_snapshot
              ls -l /experiments_snapshot
          volumeMounts:
            - name: gxa-codon-volume
              mountPath: /srv/gxa/data/gxa_codon
            - name: experiments-snapshot
              mountPath: /experiments_snapshot                 
        - name: gxa-init-tomcat-manager
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: [ "sh", "-c", "cp -r /usr/local/tomcat/webapps.dist/manager /usr/local/tomcat/webapps/" ]
          volumeMounts:
            - name: tomcat-webapps
              mountPath: /usr/local/tomcat/webapps                 
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
