apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
    app.kubernetes.io/component: webapp
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "app.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: webapp
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "app.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "app.name" . }}-webapp
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.tomcat.debug.enabled }}
          command: ["catalina.sh"]
          args: ["jpda", "run"]
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.tomcat.httpPort }}
              protocol: TCP
            {{- if .Values.tomcat.debug.enabled }}
            - name: debug
              containerPort: {{ .Values.tomcat.debug.port }}
              protocol: TCP
            {{- end }}
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          #   initialDelaySeconds: 30
          #   periodSeconds: 30
          #   timeoutSeconds: 10
          #   failureThreshold: 20
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          #   initialDelaySeconds: 30
          #   periodSeconds: 30
          #   timeoutSeconds: 10
          #   failureThreshold: 20
          env:
            # From Secret (sensitive credentials)
            - name: SOLR_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "app.fullname" . }}-secrets
                  key: SOLR_USER
            - name: SOLR_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ include "app.fullname" . }}-secrets
                  key: SOLR_PASS
            {{- include "app.proxyEnv" . | nindent 12 }}
            {{- /* These properties are required so that the bioentities SolrClient create
             in the SolrConfig class is authenticated */}}    
            - name: JAVA_TOOL_OPTIONS
              value: "-Dfile.encoding=UTF8 -Dsolr.httpclient.builder.factory=org.apache.solr.client.solrj.impl.PreemptiveBasicAuthClientBuilderFactory -Dbasicauth=\"$(SOLR_USER):$(SOLR_PASS)\""
            {{- if .Values.tomcat.debug.enabled }}
            - name: JPDA_ADDRESS
              value: {{ .Values.tomcat.debug.address | quote }}
            {{- end }}
            - name: CATALINA_OPTS
              value: "-Dhttp.proxyHost=${PROXY_HOST} -Dhttp.proxyPort=${PROXY_PORT} -Dhttps.proxyHost=${PROXY_HOST} -Dhttps.proxyPort=${PROXY_PORT} -Dhttp.nonProxyHosts=${NO_PROXY//,/|}"  

          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- /* app data mounts */}}
            - name: codon-volume
              mountPath: {{ include "app.dataDir" . }}/gxa_codon
              readOnly: true
            - name: admin-volume
              mountPath: {{ include "app.experimentsDir" . }}/admin
            - name: experiments-snapshot
              mountPath: {{ include "app.experimentsDir" . }}/magetab
              readOnly: true
            - name: codon-volume
              mountPath: {{ include "app.experimentsDir" . }}/release-metadata.json
              subPath: release-metadata.json
              readOnly: true
            - name: codon-volume
              mountPath: {{ include "app.experimentsDir" . }}/species-properties.json
              subPath: species-properties.json
              readOnly: true
            - name: services-volume
              mountPath: {{ include "app.dataDir" . }}/bioentity_properties
              subPath: fg/atlas/bioentity_properties
              readOnly: true
            - name: expdesign-volume
              mountPath: {{ include "app.expdesignDir" . }}
            - name: services-volume
              mountPath: {{ include "app.servicesDir" . }}
            - name: services-volume
              mountPath: {{ include "app.dataDir" . }}/ontology
              subPath: fg/atlas/ontology
              readOnly: true
            {{- /* webapp properties mounts */}}
            - name: configuration-properties
              mountPath: /webapp-properties/configuration.properties
              subPath: configuration.properties
            - name: tomcat-logback-xml
              mountPath: /webapp-properties/logback.xml
              subPath: logback.xml
            - name: {{ include "app.name" . }}-secrets
              mountPath: /webapp-properties/jdbc.properties
              subPath: jdbc.properties
            - name: {{ include "app.name" . }}-secrets
              mountPath: /webapp-properties/solr.properties
              subPath: solr.properties
            {{- /* tomcat config mounts */}}
            - name: {{ include "app.name" . }}-secrets
              mountPath: {{ include "app.tomcatDir" . }}/conf/tomcat-users.xml
              subPath: tomcat-users.xml
            - name: tomcat-logs
              mountPath: {{ include "app.tomcatDir" . }}/logs
            - name: tomcat-work
              mountPath: {{ include "app.tomcatDir" . }}/work
            - name: tomcat-webapps
              mountPath: {{ include "app.tomcatDir" . }}/webapps
            # Mount managed manager context.xml into the manager webapp
            - name: tomcat-server-config
              mountPath: {{ include "app.tomcatDir" . }}/webapps/manager/META-INF/context.xml
              subPath: manager-context.xml
            - name: tomcat-server-config
              mountPath: {{ include "app.tomcatDir" . }}/conf/server.xml
              subPath: server.xml
            - name: tomcat-config
              mountPath: {{ include "app.tomcatDir" . }}/conf/Catalina
      volumes:
        {{- include "app.gxaCodonVolume" . | nindent 8 }}
        {{- include "app.servicesVolume" . | nindent 8 }}
        {{- include "app.expdesignVolume" . | nindent 8 }}
        - name: experiments-snapshot
          emptyDir: {}
        - name: admin-volume
          emptyDir: {}
        - name: configuration-properties
          configMap:
            name: {{ include "app.fullname" . }}-config
            items:
              - key: configuration.properties
                path: configuration.properties
        - name: tomcat-server-config
          configMap:
            name: {{ include "app.fullname" . }}-config
            items:
              - key: server.xml
                path: server.xml
              - key: manager-context.xml
                path: manager-context.xml
        - name: tomcat-logback-xml
          configMap:
            name: {{ include "app.fullname" . }}-config
            items:
              - key: logback.xml
                path: logback.xml
        {{- include "app.secretsVolume" . | nindent 8 }}
        # TODO: do we need to make logs a persistent volume? If we use the cluster's monitoring, there is no need.
        - name: tomcat-logs
          persistentVolumeClaim:
            claimName: tomcat-logs
        - name: tomcat-work
          emptyDir: {}
        - name: tomcat-webapps
          persistentVolumeClaim:
            claimName: tomcat-webapps
        - name: tomcat-config
          emptyDir: {}
      initContainers:
        - name: "init-experiments-snapshot"
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: busybox
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["sh"]
          args:
            - "-c"
            - |
              set -vx
              EXPERIMENTS_SOURCE_DIR="{{- include "app.experimentsSourceDir" . -}}"
              if [ ! -d "$EXPERIMENTS_SOURCE_DIR" ]; then
                echo "ERROR: experimentsSourceDir does not exist: $EXPERIMENTS_SOURCE_DIR" >&2
                exit 1
              fi
              echo "experimentsSourceDir exists: $EXPERIMENTS_SOURCE_DIR"
              ln -s "$EXPERIMENTS_SOURCE_DIR"/E-* /experiments_snapshot
              echo "Number of experiments in snapshot: $(ls /experiments_snapshot | wc -l)"
          volumeMounts:
            - name: codon-volume
              mountPath: {{ include "app.dataDir" . }}/gxa_codon
            - name: services-volume
              mountPath: {{ include "app.servicesDir" . }}
            - name: experiments-snapshot
              mountPath: /experiments_snapshot
        - name: init-tomcat-manager
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: [ "sh"]
          args:
            - "-c"
            - |
              set -vx
              cp -rv {{ include "app.tomcatDir" . }}/webapps.dist/manager {{ include "app.tomcatDir" . }}/webapps/
          volumeMounts:
            - name: tomcat-webapps
              mountPath: {{ include "app.tomcatDir" . }}/webapps
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
