apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: expdesign-rwo
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  storageClassName: standard-nfs-production 
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi