apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gxa-expdesign-rwo
  labels:
    {{- include "gxa.labels" . | nindent 4 }}
spec:
  storageClassName: standard-nfs-production 
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
---
apiVersion: batch/v1
kind: Job
metadata:
  name: gxa-postgres-populator
  labels:
    {{- include "gxa.labels" . | nindent 4 }}
spec:
  template:
    spec:
      volumes:
        - name: gxa-expdesign-vol
          persistentVolumeClaim:
            claimName: gxa-expdesign-rwo
        - name: gxa-data-vol
          emptyDir: {}
        - name: atlas-web-bulk
          emptyDir: {}
        - name: gxa-secrets
          secret:
            secretName: {{ include "gxa.fullname" . }}-secrets
        - name: gxa-codon-volume
          nfs:
            server: {{ .Values.nfs.server }}
            path: /ifs/public/ro/gxa_codon
          # persistentVolumeClaim:
            # claimName: gxa-data-rox
        # TODO mount jdbc.proeprties secret as a file
      containers:
        - name: {{ include "gxa.fullname" . }}-postgres-populator
          image: openjdk:11
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-Dfile.encoding=UTF8"
            - name: HTTP_PROXY
              valueFrom:
                configMapKeyRef:
                  name: ebi-proxy
                  key: HTTP_PROXY
            - name: HTTPS_PROXY
              valueFrom:
                configMapKeyRef:
                  name: ebi-proxy
                  key: HTTPS_PROXY
            - name: http_proxy
              valueFrom:
                configMapKeyRef:
                  name: ebi-proxy
                  key: HTTP_PROXY
            - name: https_proxy
              valueFrom:
                configMapKeyRef:
                  name: ebi-proxy
                  key: HTTPS_PROXY
            - name: NO_PROXY
              valueFrom:
                configMapKeyRef:
                  name: ebi-proxy
                  key: NO_PROXY
            - name: PROXY_HOST
              valueFrom:
                configMapKeyRef:
                  name: ebi-proxy
                  key: PROXY_HOST
            - name: PROXY_PORT
              valueFrom:
                configMapKeyRef:
                  name: ebi-proxy
                  key: PROXY_PORT
            - name: EXP_IDS
              valueFrom:
                configMapKeyRef:
                  name: {{ include "gxa.fullname" . }}-config
                  key: experiment_ids
          resources:
            requests:
              memory: "2Gi"
              cpu: "2"
              ephemeral-storage: "4Gi"
            limits:
              cpu: "2"
              memory: "4Gi"
          command: ["/bin/sh", "-c"]
          args:
            - |
              set -e

              git clone --recurse-submodules --depth 1 --single-branch https://github.com/ebi-gene-expression-group/atlas-web-bulk.git
              cp /secrets/jdbc.properties /atlas-web-bulk/cli/src/main/resources/

              cd /atlas-web-bulk

              # copies secret files to resources directory
              mkdir /atlas-data/exp/magetab
              ln -s /atlas-data/exp/gxa-codon/.snapshot/{{ .Values.nfs.snapshotComponent }}/experiments/* /atlas-data/exp/magetab 

              ./gradlew \
              -PexperimentFilesLocation=/atlas-data/exp \
              -PexperimentDesignLocation=/atlas-data/expdesign \
              -Dlogging.level.root=DEBUG \
              -Dlogging.level.org.springframework.boot=DEBUG \
              -Dlogging.level.org.springframework.context.annotation=DEBUG \  
              :cli:bootRun --args="create-update-experiment -e $(echo ${EXP_IDS})
              
              ./gradlew \
              -PexperimentFilesLocation=/atlas-data/exp \
              -PexperimentDesignLocation=/atlas-data/expdesign \
              :cli:bootRun --args="update-baseline-coexpression -e $(echo ${EXP_IDS})


          volumeMounts:
            - name: gxa-expdesign-vol
              mountPath: "/atlas-data/expdesign"
            - name: gxa-data-vol
              mountPath: "/atlas-data/exp"
            - name: gxa-codon-volume
              mountPath: /atlas-data/exp/gxa-codon
            - name: gxa-codon-volume
              mountPath: /atlas-data/exp/species-properties.json
              subPath: species-properties.json  
              readOnly: true
            - name: atlas-web-bulk
              mountPath: /atlas-web-bulk
            - name: gxa-secrets
              mountPath: /secrets/jdbc.properties
              subPath: jdbc.properties
      restartPolicy: Never
  backoffLimit: 4
