{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
  annotations:
    {{- include "app.ingress.annotations" . | nindent 4 }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className | quote }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- toYaml .Values.ingress.tls | nindent 4 }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - {{- if .host }}
      host: {{ .host | quote }}
      {{- end }}
      http:
        paths:
          - path: {{ printf "%s(/|$)(.*)" $.Values.ingress.pathPrefix | quote }}
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "app.fullname" $ }}
                port:
                  number: {{ int $.Values.service.port }}
    {{- end }}
{{- end }}
