{{- if and .Values.jdbc .Values.jdbc.populator (.Values.jdbc.populator.enabled | default false) -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "app.name" . }}-postgres-populator
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  template:
    spec:
      volumes:
        {{- include "app.expdesignVolume" . | nindent 8 }}
        {{- include "app.servicesVolume" . | nindent 8 }}
        - name: {{ include "app.name" . }}-data-vol
          emptyDir: {}
        - name: webapp-volume
          emptyDir: {}
        {{- include "app.secretsVolume" . | nindent 8 }}
        {{- include "app.gxaCodonVolume" . | nindent 8 }}
        {{- include "app.gxaVolume" . | nindent 8 }}
      containers:
        - name: {{ include "app.fullname" . }}-postgres-populator
          image: openjdk:11
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-Dfile.encoding=UTF8"
            {{- include "app.proxyEnv" . | nindent 12 }}
            - name: EXP_IDS
              valueFrom:
                configMapKeyRef:
                  name: {{ include "app.fullname" . }}-config
                  key: experiment_ids
          resources:
            requests:
              memory: "2Gi"
              cpu: "2"
              ephemeral-storage: "4Gi"
            limits:
              cpu: "2"
              memory: "4Gi"
          command: ["/bin/bash", "-c"]
          args:
            - |
              set -e

              git clone --recurse-submodules --depth 1 --single-branch \
                "https://github.com/ebi-gene-expression-group/atlas-web-bulk.git"
              cp /secrets/jdbc.properties \
                 /atlas-web-bulk/cli/src/main/resources/

              cd /atlas-web-bulk/

              mkdir {{ include "app.experimentsDir" . }}/magetab
              ln -s {{ include "app.servicesDir" . }}/fg/atlas/{{ .Values.nfs.snapshotComponent }}/* \
                    {{ include "app.experimentsDir" . }}/magetab 
              ls -lt {{ include "app.experimentsDir" . }}/magetab 

              ./gradlew \
              {{ include "app.gradleCliArgs" . | indent 14 }} \
              -PexperimentFilesLocation={{ include "app.experimentsDir" . }} \
              -PexperimentDesignLocation={{ include "app.expdesignDir" . }} \
              ":cli:bootRun" --args="create-update-experiment -e $(echo ${EXP_IDS})"
              
              ./gradlew \
              {{ include "app.gradleCliArgs" . | indent 14 }} \
              -PexperimentFilesLocation={{ include "app.experimentsDir" . }} \
              -PexperimentDesignLocation={{ include "app.expdesignDir" . }} \
              ":cli:bootRun" --args="update-experiment-design -e $(echo ${EXP_IDS})"
                            
              ./gradlew \
              {{ include "app.gradleCliArgs" . | indent 14 }} \
              -PexperimentFilesLocation={{ include "app.experimentsDir" . }} \
              -PexperimentDesignLocation={{ include "app.expdesignDir" . }} \
              ":cli:bootRun" --args="update-baseline-coexpression -e $(echo ${EXP_IDS})"

              sleep 5000
          volumeMounts:
            - name: {{ include "app.name" . }}-expdesign-vol
              mountPath: "{{ include "app.expdesignDir" . }}"
            - name: {{ include "app.name" . }}-data-vol
              mountPath: "{{ include "app.experimentsDir" . }}"
            - name: services-volume
              mountPath: "{{ include "app.servicesDir" . }}"
            - name: {{ include "app.name" . }}-codon-volume
              mountPath: "{{ include "app.experimentsDir" . }}/gxa-codon"
            - name: {{ include "app.name" . }}-codon-volume
              mountPath: "{{ include "app.experimentsDir" . }}/species-properties.json"
              subPath: species-properties.json  
              readOnly: true
            - name: webapp-volume
              mountPath: /atlas-web-bulk
            - name: {{ include "app.name" . }}-secrets
              mountPath: /secrets/jdbc.properties
              subPath: jdbc.properties
      restartPolicy: Never
  backoffLimit: 4
{{- end }}