apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gxa.fullname" . }}-secrets
  labels:
    {{- include "gxa.labels" . | nindent 4 }}
type: Opaque
stringData:
  tomcat-users.xml: |
    <tomcat-users>
      <role rolename="manager-script"/>
      <user username="deployer" 
            password="{{ .Values.tomcat.deployerPassword }}" 
            roles="standard,manager-script"/>
    </tomcat-users> 
  
  jdbc.properties: |
    jdbc.url = jdbc:postgresql://pgsql-dlvm-078.ebi.ac.uk:5432/gxpatlastst
    jdbc.username = atlasprd3
    jdbc.password = {{ .Values.jdbc.password }}
    jdbc.pool = gxa

  solr.properties: |
    zk.hosts = gxa-solrcloud-zookeeper-client.anmol-test:2181
    solr.hosts = http://gxa-solrcloud-common.anmol-test/solr
    # solr.user = atlas_admin
    # solr.pass = {{ .Values.solr.password }}
    


