apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gxa.fullname" . }}-tomcat-users
  labels:
    {{- include "gxa.labels" . | nindent 4 }}
type: Opaque
stringData:
  tomcat-users.xml: |
    <tomcat-users>
      <role rolename="manager-gui"/>
      <user username="deployer" password="admin" roles="manager-gui"/>
    </tomcat-users> 