apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gxa.fullname" . }}-secrets
  labels:
    {{- include "gxa.labels" . | nindent 4 }}
type: Opaque
stringData:
  tomcat-users.xml: |
    <tomcat-users>
      <role rolename="manager-script"/>
      <user username="deployer" 
            password="{{ .Values.tomcat.deployerPassword }}" 
            roles="standard,manager-script"/>
    </tomcat-users> 
  
  jdbc.properties: |
    jdbc.url = jdbc:postgresql://pgsql-dlvmpub2-011.ebi.ac.uk:5432/gxpatlaspub
    jdbc.username = atlasprd3
    jdbc.password = {{ .Values.jdbc.password }}
    jdbc.pool = gxa

  solr.properties: |
    zk.hosts = gxa-zk-pub-hl-01:2181,gxa-zk-pub-hl-02:2181,gxa-zk-pub-hl-03:2181
    solr.hosts = http://gxa-solr-pub-hl-01:8983/solr,http://gxa-solr-pub-hl-02:8983/solr,http://gxa-solr-pub-hl-03:8983/solr,http://gxa-solr-pub-hl-04:8983/solr
    solr.user = atlas_admin
    solr.pass = {{ .Values.solr.password }}
    


