{{- if and .Values.solr .Values.solr.bulkAnalytics.jsonl .Values.solr.bulkAnalytics.jsonl.enabled | default false -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bulk-analytics-jsonl-rwo
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  storageClassName: standard-nfs-production 
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
---
apiVersion: batch/v1
kind: Job
metadata:
  name: bulk-analytics-jsonl
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  template:
    metadata:
      labels:
        {{- include "app.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "app.serviceAccountName" . }}
      volumes:
        {{- include "app.expdesignVolume" . | nindent 8 }}
        {{- include "app.servicesVolume" . | nindent 8 }}
        {{- include "app.secretsVolume" . | nindent 8 }}
        {{- include "app.gxaCodonVolume" . | nindent 8 }}
        - name: {{ include "app.name" . }}-data-vol
          emptyDir: {}
        - name: webapp-volume
          emptyDir: {}
        {{- include "app.bulkAnalyticsJsonlVolume" . | nindent 8 }}
      containers:
        - name: {{ include "app.name" . }}-solrcloud-bulk-analytics-jsonl
          image: openjdk:11
          {{- /* Expose JDWP port if debug enabled */}}
          {{- if .Values.debug.enabled }}
          ports:
            - containerPort: 5005
              name: jdwp
          {{- end }}
          env:
            # From Secret (sensitive credentials)
            - name: SOLR_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "app.fullname" . }}-secrets
                  key: SOLR_USER
            - name: SOLR_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ include "app.fullname" . }}-secrets
                  key: SOLR_PASS
            {{- /* These properties are required so that the bioentities SolrClient create 
             in the SolrConfig class is authenticated */}}
            - name: JAVA_TOOL_OPTIONS
              value: "-Dfile.encoding=UTF8 -Dsolr.httpclient.builder.factory=org.apache.solr.client.solrj.impl.PreemptiveBasicAuthClientBuilderFactory -Dbasicauth=\"$(SOLR_USER):$(SOLR_PASS)\""
            {{- include "app.proxyEnv" . | nindent 12 }}
            - name: HUMAN_EXP_IDS
              value: "E-GEOD-40611,E-GEOD-43049,E-MTAB-2836,E-MTAB-3827,E-TABM-713,E-MTAB-5214,E-PROT-1,E-PROT-28,E-PROT-39"
            - name: MOUSE_EXP_IDS
              value: "E-MEXP-1968,E-MTAB-5633"
            - name: ZEBRAFISH_EXP_IDS
              value: "E-ERAD-475"
            - name: FLY_EXP_IDS
              value: "E-MAXD-6"
            - name: WORM_EXP_IDS
              value: "E-MEXP-1810"
            - name: HORSE_EXP_IDS
              value: "E-GEOD-46858"
            - name: YEAST_EXP_IDS
              value: "E-MTAB-5128,E-MTAB-4106"
            - name: WHEAT_EXP_IDS
              value: "E-MTAB-4559,E-MTAB-5422"
            - name: PLATYPUS_EXP_IDS
              value: "E-MTAB-2909"
            - name: RICE_EXP_IDS
              value: "E-MTAB-1913,E-MTAB-3834,E-MTAB-5941"
            - name: GRASS_EXP_IDS
              value: "E-MTAB-4401"
            - name: SCHISTOSOME_EXP_IDS
              value: "E-MTAB-451"
            {{- if eq .Values.loggingLevel "DEBUG" }}
            - name: LOGGING_LEVEL_ROOT
              value: "DEBUG"
            - name: LOGGING_LEVEL_UK_AC_EBI
              value: "DEBUG"
            {{- end }}
          resources:
            requests:
              cpu: "1.5"
              memory: "4.5Gi"
              ephemeral-storage: "8Gi"
            limits:
              cpu: "2"
              memory: "6Gi"
          command: ["/bin/bash", "-c"]
          args:
            - |
              set -e

              git clone --recurse-submodules --depth 1 --single-branch https://github.com/ebi-gene-expression-group/atlas-web-bulk.git
              cp /secrets/jdbc.properties \
                 /secrets/solr.properties \
                 /atlas-web-bulk/cli/src/main/resources/

              cd /atlas-web-bulk

              mkdir {{ include "app.experimentsDir" . }}/magetab
              ln -s {{ include "app.servicesDir" . }}/fg/atlas/{{ .Values.nfs.snapshotComponent }}/* \
                    {{ include "app.experimentsDir" . }}/magetab 

              {{- if .Values.debug.enabled }}                    
              set -v
              {{- end }}
              for EXP_IDS in HUMAN_EXP_IDS MOUSE_EXP_IDS ZEBRAFISH_EXP_IDS FLY_EXP_IDS WORM_EXP_IDS HORSE_EXP_IDS YEAST_EXP_IDS WHEAT_EXP_IDS PLATYPUS_EXP_IDS RICE_EXP_IDS GRASS_EXP_IDS SCHISTOSOME_EXP_IDS
              do  
                echo "Processing experiment IDs: ${EXP_IDS}"
                ./gradlew --no-watch-fs --info \
                -PdataFilesLocation={{ include "app.dataDir" . }} \
                {{ include "app.gradleCliArgs" . | indent 14 }} \
                -PexperimentFilesLocation={{ include "app.experimentsDir" . }} \
                -PexperimentDesignLocation={{ include "app.expdesignDir" . }} \
                :cli:bootRun {{- if .Values.debug.enabled }} --debug-jvm{{- end }} \
                --args="bulk-analytics-json --output={{ include "app.bulkAnalyticsJsonlDir" . }} -e ${!EXP_IDS}"
              done
              {{- if .Values.debug.enabled }}
              sleep 60000
              {{- end }}
          volumeMounts:
            - name: services-volume
              mountPath: "{{ include "app.servicesDir" . }}"
            - mountPath: "{{ include "app.expdesignDir" . }}"
              name: {{ include "app.name" . }}-expdesign-vol
            - mountPath: "{{ include "app.experimentsDir" . }}"
              name: {{ include "app.name" . }}-data-vol
            - name: gxa-codon-volume
              mountPath: {{ include "app.experimentsDir" . }}/species-properties.json
              subPath: species-properties.json  
              readOnly: true
            - mountPath: "{{ include "app.bulkAnalyticsJsonlDir" . }}"
              name: bulk-analytics-jsonl-vol
            - name: webapp-volume
              mountPath: /atlas-web-bulk
            - name: {{ include "app.name" . }}-secrets
              mountPath: /secrets/solr.properties
              subPath: solr.properties 
            - name: {{ include "app.name" . }}-secrets
              mountPath: /secrets/jdbc.properties
              subPath: jdbc.properties

      {{/* only wait for previous job if it is enabled */}}
      {{- if and .Values.solr .Values.solr.bioentities.jsonl .Values.solr.bioentities.jsonl.enabled | default false -}}
      initContainers:
      - name: wait-for-previous-job1
        image: dtzar/helm-kubectl:3.16.2
        command: ["kubectl"]
        args:
        - "wait"
        - "--for=condition=complete"
        - "--timeout=1h"
        - "job/bioentities-populator"
      {{- end }}
      restartPolicy: Never
{{- end }}