{{- if and .Values.solr .Values.solr.bulkAnalytics.populator .Values.solr.bulkAnalytics.populator.enabled | default false -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: bulk-analytics-populator
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  template:
    metadata:
      labels:
        {{- include "app.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "app.serviceAccountName" . }}
      volumes:
        {{ include "app.bulkAnalyticsJsonlVolume" . | nindent 8 }}
        - name: scratch-bulk-analytics-vol
          ephemeral:
            volumeClaimTemplate:
              metadata:
                labels:
                  {{- include "app.labels" . | nindent 18 }}
              spec:
                accessModes: [ "ReadWriteOnce" ]
                storageClassName: "standard-nfs-production"
                resources:
                  requests:
                    storage: 200Gi
      containers:
        - name: {{ include "app.name" . }}-solrcloud-populator
          image: openjdk:11
          env:
            {{- include "app.proxyEnv" . | nindent 12 }}
            # From Secret (sensitive credentials)
            - name: SOLR_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "app.fullname" . }}-secrets
                  key: SOLR_USER
            - name: SOLR_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ include "app.fullname" . }}-secrets
                  key: SOLR_PASS
            # From ConfigMap (non-sensitive configuration)
            - name: SOLR_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ include "app.fullname" . }}-config
                  key: SOLR_HOST
            - name: SOLR_HOSTS
              valueFrom:
                configMapKeyRef:
                  name: {{ include "app.fullname" . }}-config
                  key: SOLR_HOST
            - name: SOLR_COLLECTION
              valueFrom:
                configMapKeyRef:
                  name: {{ include "app.fullname" . }}-config
                  key: SOLR_BULK_ANALYTICS_COLLECTION
            - name: SOLR_NUM_SHARDS
              valueFrom:
                configMapKeyRef:
                  name: {{ include "app.fullname" . }}-config
                  key: SOLR_NUM_SHARDS
            - name: NUM_DOCS_PER_BATCH
              value: "10000"
            - name: SOLR_COMMIT_DOCS
              value: "500000"
            - name: SCHEMA_VERSION
              value: "1"
            # Consider moving this to an export line in the script (?)
            - name: SOLR_PROCESSORS
              value: "dedupe"
            - name: GIT_BRANCH
              value: {{ .Values.solr.bulkAnalytics.populator.gitBranch | default "develop" | quote }}
          resources:
            requests:
              cpu: 0.5
              memory: 256Mi
            limits:
              cpu: 0.55
              memory: 1Gi
          command: ["/bin/bash", "-c"]
          args:
            - |  
              set -v            
              mkdir /work
              
              cd /work
              
              git clone --recurse-submodules --depth 1 --single-branch --branch ${GIT_BRANCH} https://github.com/ebi-gene-expression-group/index-bioentities.git
              git clone --recurse-submodules --depth 1 --single-branch --branch ${GIT_BRANCH} https://github.com/ebi-gene-expression-group/index-gxa.git
              
              cd /work/index-gxa/bin
              ./create-bulk-analytics-collection.sh
              set -vx
              ./create-bulk-analytics-schema.sh

              # We go back to index-bioentities/bin because the solr-jsonl-chunk-loader.sh script isn't in the solr-bulk repository
              cd {{ include "app.dataDir" . }}/scratch
              JSONL_DIR="{{- include "app.bulkAnalyticsJsonlDir" . -}}"
              echo "found $(ls -Sr ${JSONL_DIR}/*.jsonl | wc -l) jsonl files"
              for FILE in `ls -Sr ${JSONL_DIR}/*.jsonl`
              do
                INPUT_JSONL=${FILE} /work/index-bioentities/bin/solr-jsonl-chunk-loader.sh \
                  >> /dev/stdout 2>&1 \
                  && echo "SUCCESS: Processed file: ${FILE}" \
                  || echo "ERROR: Failed to process file: ${FILE}"
              done
              {{- if .Values.debug.enabled }}
              sleep 60000
              {{- end }}
          volumeMounts:
            - mountPath: "{{ include "app.bulkAnalyticsJsonlDir" . }}"
              name: bulk-analytics-jsonl-vol
            - mountPath: "{{ include "app.dataDir" . }}/scratch"
              name: scratch-bulk-analytics-vol
      {{/* only wait for previous job if it is enabled */}}
      {{- if and .Values.solr .Values.solr.bulkAnalytics.jsonl .Values.solr.bulkAnalytics.jsonl.enabled | default false -}}
      initContainers:
        - name: wait-for-previous-job
          image: dtzar/helm-kubectl:3.16.2
          command: ["kubectl"]
          args:
          - "wait"
          - "--for=condition=complete"
          - "--timeout=1h"
          - "job/bulk-analytics-jsonl"
      {{- end }}
      restartPolicy: Never
{{- end }}