apiVersion: batch/v1
kind: Job
metadata:
  name: gxa-solrcloud-bioentities-populator
  namespace: jenkins-gene-expression
spec:
  template:
    spec:
      volumes:
        - name: gxa-bioentities-jsonl-vol
          persistentVolumeClaim:
            claimName: gxa-bioentities-jsonl-rwo
      containers:
        - name: gxa-solrcloud-populator
          image: quay.io/ebigxa/gxa-atlas-web-bulk-postgres-solrcloud-populator:latest
          env:
            - name: SOLR_HOST
              value: "gxa-solrcloud-0.gxa-solrcloud-headless.jenkins-gene-expression.svc.cluster.local:8983"
            - name: SOLR_HOSTS
              value: "gxa-solrcloud-0.gxa-solrcloud-headless.jenkins-gene-expression.svc.cluster.local:8983 gxa-solrcloud-1.gxa-solrcloud-headless.jenkins-gene-expression.svc.cluster.local:8983 gxa-solrcloud-2.gxa-solrcloud-headless.jenkins-gene-expression.svc.cluster.local:8983 gxa-solrcloud-3.gxa-solrcloud-headless.jenkins-gene-expression.svc.cluster.local:8983"
            - name: SOLR_NUM_SHARDS
              value: "4"
            - name: NUM_DOCS_PER_BATCH
              value: "20000"
            - name: SOLR_COLLECTION
              value: "bioentities"
            - name: SCHEMA_VERSION
              value: "1"
          resources:
            requests:
              memory: 2Gi
          args:
            - |
              cd /root/index-bioentities/bin
              ./create-bioentities-collection.sh
              ./create-bioentities-schema.sh
              ./create-bioentities-suggesters.sh

              for FILE in `ls /atlas-data/bioentities-jsonl/*.jsonl`
              do
                INPUT_JSONL=${FILE} ./solr-jsonl-chunk-loader.sh >> /dev/stdout 2>&1
              done
              ./build-suggesters.sh
          volumeMounts:
            - mountPath: "/atlas-data/bioentities-jsonl"
              name: gxa-bioentities-jsonl-vol
      restartPolicy: Never
