apiVersion: batch/v1
kind: CronJob
metadata:
  name: resources-optimizer
spec:
  schedule: "@hourly"
  startingDeadlineSeconds: 40
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          serviceAccountName: admin-jenkins-gene-expression
          nodeSelector:
            cloud.google.com/gke-spot: "true"
          containers:
          - name: resources-optimizer
            image: bitnami/kubectl:latest
            command: ["/bin/bash"]
            args: ["/scripts-dir/main.sh"]
            env:
            - name: LABELS_FILTER
              value: "jenkins in (slave)"
            - name: STATEFULSET
              value: "scxa"
            volumeMounts:
            - name: script-vol
              mountPath: /scripts-dir
          volumes:
          - name: script-vol
            configMap:
              name: script-configmap
