apiVersion: v2
name: mongodb
description: A Helm chart for deploying MongoDB via the Bitnami chart

type: application

version: 0.1.0

appVersion: "8.0"

dependencies:
  - name: mongodb
    repository: oci://registry-1.docker.io/bitnamicharts
    version: "16.5.45"
