kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "app.name" . }}-expdesign-rox
  namespace: jenkins-gene-expression
spec:
  dataSource:
    apiGroup: snapshot.storage.k8s.io
    kind: VolumeSnapshot
    name: {{ include "app.name" . }}-expdesign-rwo-snapshot
  accessModes:
    - ReadOnlyMany
  storageClassName: premium-rwo
  resources:
    requests:
      storage: 1Gi
