apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: gxa-expdesign-rwo-snapshot
  namespace: jenkins-gene-expression
spec:
  volumeSnapshotClassName: snapshot-class
  source:
    persistentVolumeClaimName: gxa-expdesign-rwo

