apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.fullname" . }}-config
  labels:
    {{- include "app.labels" . | nindent 4 }}
data:
  species: |
    danio_rerio homo_sapiens equus_caballus drosophila_melanogaster
    caenorhabditis_elegans mus_musculus oryza_indica anas_platyrhynchos
    oryza_sativa brachypodium_distachyon schistosoma_mansoni zea_mays
    saccharomyces_cerevisiae schizosaccharomyces_pombe

  experiment_ids: {{ .Values.experiment_ids | quote }}


  # Solr configuration
  SOLR_HOST: "{{ include "app.solrHost" . }}"
  SOLR_ZK_HOSTS: "{{ include "app.solrZkHosts" . }}"
  SOLR_SCXA_ANALYTICS_COLLECTION: "{{ .Values.solr.scxaAnalytics.collection  }}"
  SOLR_SCXA_GENE2EXPERIMENT_COLLECTION: "{{ .Values.solr.gene2experiment.collection  }}"
  SOLR_NUM_SHARDS: "{{ .Values.solr.numShards | default "4" }}"
  SOLR_TIMEOUT: "{{ .Values.solr.timeout | default "30000" }}"

