{{- if .Values.nginx.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-cache
  annotations:
    helm.sh/resource-policy: keep
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.nginx.cache.storageClassName | default "standard-nfs-production" }}
  accessModes:
    - {{ .Values.nginx.cache.accessMode | default "ReadWriteMany" }}
  resources:
    requests:
      storage: {{ .Values.nginx.cache.storageSize | default "2Gi" }}
{{- end }}
