{{- if and .Values.jdbc .Values.jdbc.populator (.Values.jdbc.populator.enabled | default false) -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "app.name" . }}-postgres-populator
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  template:
    spec:
      volumes:
        {{- include "app.secretsVolume" . | nindent 8 }}
        {{- include "app.scxaExperimentsVolume" . | nindent 8 }}

{{/*        {{- include "app.expdesignVolume" . | nindent 8 }}*/}}
{{/*        {{- include "app.servicesVolume" . | nindent 8 }}*/}}
{{/*        - name: {{ include "app.name" . }}-data-vol*/}}
{{/*          emptyDir: {}*/}}
{{/*        - name: webapp-volume*/}}
{{/*          emptyDir: {}*/}}
{{/*        {{- include "app.secretsVolume" . | nindent 8 }}*/}}
{{/*        {{- include "app.gxaCodonVolume" . | nindent 8 }}*/}}
{{/*        {{- include "app.gxaVolume" . | nindent 8 }}*/}}
      containers:
        - name: {{ include "app.fullname" . }}-postgres-populator
          image: openjdk:11
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-Dfile.encoding=UTF8"
            {{- include "app.proxyEnv" . | nindent 12 }}
            - name: EXP_IDS
              valueFrom:
                configMapKeyRef:
                  name: {{ include "app.fullname" . }}-config
                  key: experiment_ids
            # From Secret (sensitive credentials)
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ include "app.fullname" . }}-config
                  key: POSTGRES_HOST
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: {{ include "app.fullname" . }}-config
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "app.fullname" . }}-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "app.fullname" . }}-secrets
                  key: POSTGRES_PASSWORD
          resources:
            requests:
              memory: "2Gi"
              cpu: "2"
              ephemeral-storage: "4Gi"
            limits:
              cpu: "2"
              memory: "4Gi"
          command: ["/bin/bash", "-c"]
          args:
            - |
              set -ev

              mkdir /work && cd /work

              git clone --recurse-submodules --depth 1 https://github.com/ebi-gene-expression-group/atlas-web-single-cell.git
              git clone --recurse-submodules https://github.com/ebi-gene-expression-group/db-scxa.git

              cd atlas-web-single-cell

              # Creating the experiments is required because certain scripts below use experiment.accession as a foreign key.
              # We get the experiment designs as a side benefit: they are necessary for ITs and for running the web app
              ./gradlew \
              {{ include "app.gradleCliArgs" . | indent 14 }} \
              -PexperimentFilesLocation={{ include "app.experimentsDir" . }} \
              -PexperimentDesignLocation={{ include "app.expdesignDir" . }} \
              -PjdbcUrl=jdbc:postgresql://${POSTGRES_HOST}:5432/${POSTGRES_DB} \
              -PjdbcUsername=${POSTGRES_USER} \
              -PjdbcPassword=${POSTGRES_PASSWORD} \
              :cli:bootRun --args="create-update-experiment -e $(echo ${EXP_IDS} | sed -e "s/ /,/g")"

              # The last commit before v19 was introduced...
              if [ "${SCHEMA_VERSION}" = "18" ] ; then
                cd /root/db-scxa
                git checkout 1236753d3d799effa4d24fa9bdfb9292c66309ab
              fi

              cd /work/db-scxa/bin
              export PATH=.:$${PATH}
              export dbConnection=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:5432/${POSTGRES_DB}

              for EXP_ID in ${EXP_IDS}
              do
                EXPRESSION_TYPE=aggregated_filtered_normalised_counts \
                EXP_ID=$${EXP_ID} \
                EXPERIMENT_MATRICES_PATH=/atlas-data/exp/magetab/$${EXP_ID} ./load_db_scxa_analytics.sh

                if [ "${SCHEMA_VERSION}" = "18" ]; then
                  EXP_ID=$${EXP_ID} SCRATCH_DIR=/atlas-data/exp/magetab/$${EXP_ID} ./load_db_scxa_dimred.sh
                else
                  EXP_ID=$${EXP_ID} \
                  CONDENSED_SDRF_FILE=/atlas-data/exp/magetab/$${EXP_ID}/$${EXP_ID}.condensed-sdrf.tsv \
                  SDRF_FILE=/atlas-data/exp/magetab/$${EXP_ID}/$${EXP_ID}.sdrf.txt ./load_exp_design.sh

                  # Copied from db-scxa/tests/test-dimred-load.sh
                  ls /atlas-data/exp/magetab/$${EXP_ID}/$${EXP_ID}.tsne*.tsv | while read -r l; do
                    DIMRED_TYPE=tsne \
                    DIMRED_FILE_PATH=$$l \
                    DIMRED_PARAM_JSON='[{"perplexity": '$(echo "$$l" | sed 's/.*[^0-9]\([0-9]*\).tsv/\1/g')'}]' \
                    SCRATCH_DIR=/atlas-data/exp/magetab/$${EXP_ID} \
                    load_db_scxa_dimred.sh $${dbConnection} $${EXP_ID} $${DIMRED_TYPE} $${DIMRED_FILE_PATH} "$${DIMRED_PARAM_JSON}"
                  done

                  ls /atlas-data/exp/magetab/$${EXP_ID}/$${EXP_ID}.umap*.tsv | while read -r l; do
                    DIMRED_TYPE=umap \
                    DIMRED_FILE_PATH=$$l \
                    DIMRED_PARAM_JSON='[{"n_neighbors": '$(echo "$$l" | sed 's/.*[^0-9]\([0-9]*\).tsv/\1/g')'}]' \
                    SCRATCH_DIR=/atlas-data/exp/magetab/$${EXP_ID} \
                    load_db_scxa_dimred.sh $${dbConnection} $${EXP_ID} $${DIMRED_TYPE} $${DIMRED_FILE_PATH} "$${DIMRED_PARAM_JSON}"
                  done
                fi

                EXP_ID=$${EXP_ID} \
                EXPERIMENT_CLUSTERS_FILE=/atlas-data/exp/magetab/$${EXP_ID}/$${EXP_ID}.clusters.tsv \
                CONDENSED_SDRF_TSV=/atlas-data/exp/magetab/$${EXP_ID}/$${EXP_ID}.condensed-sdrf.tsv \
                ./load_db_scxa_cell_clusters.sh

                EXP_ID=$${EXP_ID} \
                CLUSTERS_FORMAT=SCANPY \
                EXPERIMENT_MGENES_PATH=/atlas-data/exp/magetab/$${EXP_ID} \
                ./load_db_scxa_marker_genes.sh
              done

              ./reindex_tables.sh

          volumeMounts:
            - name: {{ include "app.name" . }}-exp-volume
              mountPath: {{ include "app.dataDir" . }}/exp/magetab
            - name: {{ include "app.name" . }}-exp-volume
              mountPath: {{ include "app.expdesignDir" . }}
              subPath: expDesign
            - name: {{ include "app.name" . }}-secrets
              mountPath: /webapp-properties/jdbc.properties
              subPath: jdbc.properties

{{/*            - name: {{ include "app.name" . }}-expdesign-vol*/}}
{{/*              mountPath: "{{ include "app.expdesignDir" . }}"*/}}
{{/*            - name: {{ include "app.name" . }}-data-vol*/}}
{{/*              mountPath: "{{ include "app.experimentsDir" . }}"*/}}
{{/*            - name: services-volume*/}}
{{/*              mountPath: "{{ include "app.servicesDir" . }}"*/}}
{{/*            - name: {{ include "app.name" . }}-codon-volume*/}}
{{/*              mountPath: "{{ include "app.experimentsDir" . }}/gxa-codon"*/}}
{{/*            - name: {{ include "app.name" . }}-codon-volume*/}}
{{/*              mountPath: "{{ include "app.experimentsDir" . }}/species-properties.json"*/}}
{{/*              subPath: species-properties.json  */}}
{{/*              readOnly: true*/}}
{{/*            - name: webapp-volume*/}}
{{/*              mountPath: /atlas-web-bulk*/}}
{{/*            - name: {{ include "app.name" . }}-secrets*/}}
{{/*              mountPath: /secrets/jdbc.properties*/}}
{{/*              subPath: jdbc.properties*/}}
      restartPolicy: Never
  backoffLimit: 4
{{- end }}