apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gradle-7.0-ro-dep-cache-rwo
  namespace: jenkins-gene-expression
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

