kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: gradle-7.0-ro-dep-cache-rox
  namespace: jenkins-gene-expression
spec:
  dataSource:
    apiGroup: snapshot.storage.k8s.io
    kind: VolumeSnapshot
    name: gradle-7.0-ro-dep-cache-rwo-snapshot
  accessModes:
    - ReadOnlyMany
  storageClassName: premium-rwo
  resources:
    requests:
      storage: 1Gi
