apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.fullname" . }}-secrets
  labels:
    {{- include "app.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: delete
type: Opaque
stringData:
  {{- if and (not (empty .Values.jdbc)) .Values.jdbc.createSecret }}
  jdbc.properties: |
    jdbc.url = {{ .Values.jdbc.url }}
    jdbc.username = atlasprd3
{{/*    jdbc.password = {{ .Values.jdbc.password }} TODO : where is this coming from?*/}}
    jdbc.pool = gxa
  {{- end }}

  {{- if and (not (empty .Values.solr)) .Values.solr.createSecret }}
  solr.properties: |
    zk.hosts = {{ include "app.solrZkHosts" . }}
    {{- /* 
      for the Java app the solr.hosts property is actually the solr URL 
      (including http:// and port)
    */}}
    solr.hosts = http://{{ include "app.solrHost" . }}/solr
    solr.user = {{ .Values.solr.user }}
{{/*    solr.pass = {{ .Values.solr.password }} TODO : where is this coming from? */}}
    solr.collection = {{ .Values.solr.bioentities.collection }}
    solr.numShards = {{ .Values.solr.numShards | default "4" }}
    solr.timeout = {{ .Values.solr.timeout | default "30000" }}
  # Individual credentials for environment variables
  SOLR_USER: {{ .Values.solr.user }}
{{/*  SOLR_PASS: {{ .Values.solr.password }} TODO : where is this coming from? */}}
  {{- end }}

{{- /* Optional docker-registry Secret for image pulls */}}
{{- if and .Values.registrySecret .Values.registrySecret.create | default false }}
---
apiVersion: v1
kind: Secret
metadata:
{{/*  name: {{ default (printf "%s-registry" (include "app.fullname" .)) .Values.registrySecret.name }} TODO : where is this coming from? */}}
  labels:
    {{- include "app.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
{{/*  .dockerconfigjson: {{ required "registrySecret.dockerconfigjson must be set when registrySecret.create=true" .Values.registrySecret.dockerconfigjson | b64enc | quote }} TODO : where is this coming from? */}}
{{- end }}
