apiVersion: v2
icon: "https://www.ebi.ac.uk/gxa/resources/images/expression-atlas.png"
name: gxa
description: A Helm chart for Kubernetes for the deployment of Gene Expression Atlas

type: application

version: 0.1.1

appVersion: "37.1.1"

dependencies:
  - name: bioentities-collection
    version: "0.1.0"
    repository: "file://../bioentities-collection"