# values for gxa test env
environment: test

experiment_ids: "E-CURD-23,E-CURD-30,E-ERAD-475,E-GEOD-16879,E-GEOD-18068,E-GEOD-26284,E-GEOD-36391,E-GEOD-40611,E-GEOD-42891,E-GEOD-43049,E-GEOD-43245,E-GEOD-46858,E-GEOD-47962,E-GEOD-52405,E-GEOD-54272,E-GEOD-58856,E-GEOD-61857,E-GEOD-62671,E-GEOD-77637,E-GTEX-8,E-MAXD-6,E-MEXP-1810,E-MEXP-1968,E-MTAB-10583,E-MTAB-11671,E-MTAB-1913,E-MTAB-2137,E-MTAB-2770,E-MTAB-2812,E-MTAB-2836,E-MTAB-2848,E-MTAB-2909,E-MTAB-3358,E-MTAB-3578,E-MTAB-3579,E-MTAB-3717,E-MTAB-3719,E-MTAB-3726,E-MTAB-3727,E-MTAB-3819,E-MTAB-3826,E-MTAB-3827,E-MTAB-3834,E-MTAB-3838,E-MTAB-3983,E-MTAB-4021,E-MTAB-4045,E-MTAB-4106,E-MTAB-4344,E-MTAB-4401,E-MTAB-4404,E-MTAB-451,E-MTAB-4559,E-MTAB-4748,E-MTAB-4754,E-MTAB-4818,E-MTAB-4840,E-MTAB-5071,E-MTAB-5072,E-MTAB-5073,E-MTAB-5117,E-MTAB-5128,E-MTAB-5200,E-MTAB-5422,E-MTAB-5423,E-MTAB-552,E-MTAB-5633,E-MTAB-5941,E-MTAB-6782,E-MTAB-7663,E-MTAB-7887,E-MTAB-8621,E-MTAB-8641,E-MTAB-8758,E-PROT-28,E-PROT-3,E-PROT-39,E-PROT-5,E-TABM-713"

tomcat:
  createSecret: true

loggingLevel: INFO

debug:
  enabled: true
  port: 5005
  jvm: true

jdbc:
  url: "jdbc:postgresql://pgsql-dlvm-078.ebi.ac.uk:5432/gxpatlastst"
  createSecret: true
  populator:
    enabled: false

solr:
  namespace: gxa-dev-solrcloud
  user: admin
  createSecret: true
  bulkAnalytics:
    jsonl:
      enabled: true
    populator:
      enabled: true
      gitBranch: feature/amnon-GXA-333-populate-solr-on-k8s
    collection: bulk-analytics
    loggingLevel: DEBUG
  bioentities:
    jsonl:
      enabled: false
    populator:
      enabled: false
      gitBranch: feature/amnon-GXA-333-populate-solr-on-k8s
    collection: bioentities
