# values for gxa test env
environment: staging

tomcat:
  createSecret: true
  debug:
    enabled: false

loggingLevel: INFO

nfs:
  snapshotComponent: experiments_test

jdbc:
  # TODO: change when we have the new database
  #url: "jdbc:postgresql://pgsql-hlvm-038:5432/gxpatlaspro"
  user: atlasprd3
  pool: gxa
  createSecret: true


solr:
  namespace: gxa-staging-solrcloud
  user: admin
  createSecret: true
