# values for gxa fallback env (hx-wp-webadmin-121 / fg-fallback)
environment: fallback

tomcat:
  createSecret: true
  debug:
    enabled: false

loggingLevel: INFO

jdbc:
  url: "jdbc:postgresql://pgsql-dlvmpubfall2-019.ebi.ac.uk:5432/gxpatlaspro"
  user: atlasprd3
  pool: gxa
  createSecret: true

solr:
  namespace: gxa-fallback-solrcloud
  user: admin
  createSecret: true

# see https://embl.service-now.com/esc?id=kb_article&sysparm_article=KB0011170
nfs:
  server: "hx-isi-srv-vlan157.ebi.ac.uk"
  publicPath: /ifs/public-r

autoscaling:
  enabled: false