# values for gxa test env
environment: staging

tomcat:
  createSecret: true
  debug:
    enabled: false

loggingLevel: INFO

jdbc:
  # Shared with ci (populate source): pgsql-hlvm-147
  url: "jdbc:postgresql://pgsql-hlvm-147.ebi.ac.uk:5432/gxpatlaspro"
  user: atlasprd3
  pool: gxa
  createSecret: true


solr:
  namespace: gxa-staging-solrcloud
  user: admin
  createSecret: true
