# values for gxa test env

# NOTE: E-MTAB-5214 fails, it's removed from the the list
# experiment_ids: "E-ERAD-475,E-GEOD-40611,E-GEOD-43049,E-GEOD-46858,E-MAXD-6,E-MEXP-1810,E-MEXP-1968,E-MTAB-1913,E-MTAB-2836,E-MTAB-2909,E-MTAB-3827,E-MTAB-3834,E-MTAB-4401,E-MTAB-451,E-MTAB-4559,E-MTAB-5128,E-MTAB-5422,E-MTAB-5633,E-MTAB-5941,E-TABM-713,E-PROT-1,E-MTAB-4106,E-PROT-28,E-PROT-39"
experiment_ids: "E-GEOD-40611.tsv,E-GEOD-43049.tsv,E-MAXD-6.tsv,E-MEXP-1810.tsv,E-MEXP-1968.tsv,E-MTAB-1913.tsv,E-MTAB-2909.tsv,E-MTAB-3834.tsv,E-MTAB-4106.tsv,E-MTAB-4559.tsv,E-MTAB-5128.tsv,E-MTAB-5422.tsv,E-MTAB-5633.tsv,E-MTAB-5941.tsv,E-PROT-1.tsv,E-PROT-28.tsv,E-PROT-39.tsv,E-TABM-713.tsv"

jdbc:
  url: "jdbc:postgresql://pgsql-dlvm-078.ebi.ac.uk:5432/gxpatlastst"