#!/usr/bin/env bash
# Initialize (once) and unseal OpenBao on fg-public.
# Writes charts/openbao/.secrets-init-public.yaml (gitignored).
set -euo pipefail

CONTEXT="${K8S_CONTEXT:-fg-public}"
NS="${OPENBAO_NAMESPACE:-openbao}"
POD="${OPENBAO_POD:-openbao-0}"
INIT_FILE="${OPENBAO_INIT_FILE:-charts/openbao/.secrets-init-public.yaml}"
STATUS_FILE="$(mktemp)"
trap 'rm -f "$STATUS_FILE"' EXIT

wait_for_bao() {
  echo "Waiting for ${POD} to answer bao status..."
  kubectl --context "${CONTEXT}" -n "${NS}" wait "pod/${POD}" \
    --for=condition=PodScheduled --timeout=120s >/dev/null 2>&1 || true
  local i
  for i in $(seq 1 60); do
    # `bao status` exits 2 while sealed; still write the table to STATUS_FILE.
    kubectl --context "${CONTEXT}" -n "${NS}" exec "${POD}" -- \
        bao status >"${STATUS_FILE}" 2>/dev/null || true
    if grep -q 'Initialized' "${STATUS_FILE}" 2>/dev/null; then
      return 0
    fi
    sleep 5
  done
  echo "Error: ${POD} did not become reachable (image pull?)" >&2
  kubectl --context "${CONTEXT}" -n "${NS}" get pods,events >&2
  return 1
}

write_init_file() {
  local json_file="$1"
  python3 - "${json_file}" "${INIT_FILE}" <<'PY'
import json, sys
from pathlib import Path

data = json.loads(Path(sys.argv[1]).read_text())
out = Path(sys.argv[2])
lines = [
    "# Generated by bao operator init. Never commit. Copy off-cluster.",
    f"unseal_threshold: {data['unseal_threshold']}",
    f"root_token: {json.dumps(data['root_token'])}",
    "unseal_keys_b64:",
]
for key in data["unseal_keys_b64"]:
    lines.append(f"  - {json.dumps(key)}")
out.write_text("\n".join(lines) + "\n")
print(f"Wrote {out}")
PY
}

unseal_from_file() {
  python3 - "${INIT_FILE}" "${OPENBAO_ADDR:-https://openbao.hh-webadmin-35.wp-k8s.ebi.ac.uk}" <<'PY'
import json, ssl, sys, urllib.error, urllib.request
from pathlib import Path

init_file = Path(sys.argv[1])
addr = sys.argv[2].rstrip("/")
threshold = 3
keys = []
try:
    import yaml  # type: ignore

    data = yaml.safe_load(init_file.read_text()) or {}
    threshold = int(data.get("unseal_threshold") or 3)
    keys = list(data.get("unseal_keys_b64") or [])
except ImportError:
    for raw in init_file.read_text().splitlines():
        line = raw.strip()
        if line.startswith("unseal_threshold:"):
            threshold = int(line.split(":", 1)[1].strip())
        elif line.startswith("- "):
            keys.append(json.loads(line[2:]))
if len(keys) < threshold:
    raise SystemExit(f"{init_file}: need {threshold} unseal keys, found {len(keys)}")

ctx = ssl._create_unverified_context()
sealed = True
for key in keys[:threshold]:
    req = urllib.request.Request(
        f"{addr}/v1/sys/unseal",
        data=json.dumps({"key": key}).encode(),
        method="POST",
        headers={"Content-Type": "application/json"},
    )
    try:
        with urllib.request.urlopen(req, context=ctx, timeout=30) as resp:
            body = json.loads(resp.read() or b"{}")
    except urllib.error.HTTPError as exc:
        raise SystemExit(f"unseal: HTTP {exc.code}") from exc
    sealed = bool(body.get("sealed", True))
    print(f"Unseal progress {body.get('progress')}/{body.get('t')}")
    if not sealed:
        break
if sealed:
    raise SystemExit("OpenBao is still sealed after submitting threshold keys")
print("OpenBao is unsealed")
PY
}

wait_for_bao
INITIALIZED="$(awk '/Initialized/ {print $2}' "${STATUS_FILE}")"
SEALED="$(awk '/Sealed/ {print $2}' "${STATUS_FILE}")"

if [ "${INITIALIZED}" != "true" ]; then
  echo "Initializing OpenBao (keys -> ${INIT_FILE})..."
  INIT_JSON="$(mktemp)"
  kubectl --context "${CONTEXT}" -n "${NS}" exec "${POD}" -- \
    bao operator init -format=json >"${INIT_JSON}"
  write_init_file "${INIT_JSON}"
  rm -f "${INIT_JSON}"
  SEALED=true
fi

if [ "${SEALED}" = "true" ]; then
  if [ ! -f "${INIT_FILE}" ]; then
    echo "Error: OpenBao is sealed but ${INIT_FILE} is missing." >&2
    exit 1
  fi
  echo "Unsealing OpenBao..."
  unseal_from_file
fi

kubectl --context "${CONTEXT}" -n "${NS}" exec "${POD}" -- bao status
echo "OpenBao UI: https://openbao.hh-webadmin-35.wp-k8s.ebi.ac.uk"
echo "Init file (gitignored): ${INIT_FILE}"
