apiVersion: batch/v1
kind: Job
metadata:
  name: gxa-data-populator
  namespace: jenkins-gene-expression
spec:
  template:
    spec:
      containers:
        - args:
            - lftp -e "get /pub/databases/arrayexpress/data/atlas/atlas-ci/species-properties.json
              -o /gxa-data; exit" ftp.ebi.ac.uk; lftp -e "get /pub/databases/arrayexpress/data/atlas/atlas-ci/release-metadata.json
              -o /gxa-data; exit" ftp.ebi.ac.uk; mkdir /gxa-data/magetab; for EXP_ID in
              $(EXP_IDS); do lftp -e "mirror -vvv /pub/databases/arrayexpress/data/atlas/experiments/${EXP_ID}
              /gxa-data/magetab/ --exclude old/ --exclude archive/; exit" ftp.ebi.ac.uk;
              done; lftp -e "mirror -vvv /pub/databases/arrayexpress/data/atlas/ontology
              /gxa-data-ontology; exit" ftp.ebi.ac.uk;
          command:
            - sh
            - -c
          env:
            - name: EXP_IDS
              value: E-ERAD-475 E-GEOD-40611 E-GEOD-43049 E-GEOD-46858 E-MAXD-6 E-MEXP-1810
                E-MEXP-1968 E-MTAB-1913 E-MTAB-2770 E-MTAB-2836 E-MTAB-2909 E-MTAB-3579
                E-MTAB-3827 E-MTAB-3834 E-MTAB-4106 E-MTAB-4401 E-MTAB-451 E-MTAB-4559
                E-MTAB-5128 E-MTAB-5200 E-MTAB-5214 E-MTAB-5422 E-MTAB-5423 E-MTAB-5633
                E-MTAB-5941 E-PROT-1 E-PROT-15 E-PROT-28 E-PROT-39 E-TABM-713
          image: takkatakka/lftp
          imagePullPolicy: Always
          name: gxa-data-populator
          resources:
            limits:
              cpu: 500m
              ephemeral-storage: 1Gi
              memory: 2Gi
            requests:
              cpu: 500m
              ephemeral-storage: 1Gi
              memory: 2Gi
          securityContext:
            capabilities:
              drop:
                - NET_RAW
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /gxa-data
              name: gxa-data-vol
            - mountPath: /gxa-data-ontology
              name: gxa-data-ontology-vol
      dnsPolicy: ClusterFirst
      nodeSelector:
        topology.kubernetes.io/zone: europe-west2-a
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      terminationGracePeriodSeconds: 30
      tolerations:
        - effect: NoSchedule
          key: kubernetes.io/arch
          operator: Equal
          value: amd64
      volumes:
        - name: gxa-data-vol
          persistentVolumeClaim:
            claimName: gxa-data-rwo
        - name: gxa-data-ontology-vol
          persistentVolumeClaim:
            claimName: gxa-data-ontology-rwo
  backoffLimit: 4